# Generated by Django 3.0.8 on 2020-07-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0002_fenquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fenquiry',
            name='zipcode',
            field=models.IntegerField(),
        ),
    ]
